name: Jira Webhook Trigger

on:
  repository_dispatch:
    types: do-something
  workflow_dispatch:

jobs:
  jira_trigger_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print variables
        run: |
         echo ${{ github.event.client_payload.jira_issue_key }}
         echo ${{ github.event.client_payload.jira_assignee }}
