# name: Jira Webhook Trigger

on:
  # repository_dispatch:
  #   types: do-something
  workflow_dispatch:

# jobs:
#   jira_trigger_job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Print variables
#         run: |
#          echo ${{ github.event.client_payload.jira_issue_key }}
#          echo ${{ github.event.client_payload.jira_assignee }}

name: Triggered from Jira

on:
  repository_dispatch:
    types: do-something # Ensure this matches `event_type` in Jira
    workflow_dispatch:
    
jobs:
  process_jira_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # - name: Print Full Payload
      #   run: echo "${{ toJson(github.event.client_payload) }}"

      # - name: Print Issue Key
      #   run: echo "Issue Key=${{ github.event.client_payload.issueKey }}"

      # - name: Print Summary
      #   run: echo "Summary=${{ github.event.client_payload.summary }}"

      # - name: Print env values
      #   run: cat $GITHUB_ENV

      # - name: Print Custom Field
      #   run: echo "snow_chg_id:" ${{ github.event.client_payload.snow_chg_id }}

      # - name: Print assignee
      #   run: echo "Assignee:" ${{ github.event.client_payload.assignee }}

      # - name: Print description
      #   run: echo "Description:" ${{ github.event.client_payload.description }}

      - name: Update charm id in jira
        shell: bash
        # env:
        #   ISSUE_KEY: "TESTING-18"
        #   CHARM_ID: "1234567"  # Set CHARM_ID directly
        run: |
           echo "${{secrets.name}}"
           # set -x
           # chmod +x .github/workflows/jwt-token.sh
           # sh .github/workflows/jwt-token.sh
        
