name: Jira Webhook Trigger

on:
  repository_dispatch:
    types: do-something
  workflow_dispatch:

jobs:
  jira_trigger_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
