name: Jira Webhook Trigger

on:
  repository_dispatch:
    types: do-something
  workflow_dispatch:

jobs:
  jira_trigger_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo "Hello, ${{ github.event.inputs.environment }}!"
