# name: Jira Webhook Trigger

# on:
#   repository_dispatch:
#     types: do-something
#   workflow_dispatch:

# jobs:
#   jira_trigger_job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Print variables
#         run: |
#          echo ${{ github.event.client_payload.jira_issue_key }}
#          echo ${{ github.event.client_payload.jira_assignee }}

name: Triggered from Jira

on:
  repository_dispatch:
    types: do-something #Ensure this matches `event_type` in Jira

jobs:
  process_jira_data:
    runs-on: ubuntu-latest
   
    steps:
      - name: Print Full Payload
        run: echo "${{ toJson(github.event.client_payload) }}" > my_var.txt
      - name: Print Issue Key
        run: echo "Issue Key:" ${{ github.event.client_payload.issueKey }}
      - name: Print Summary
        run: echo "Summary:" ${{ github.event.client_payload.summary }}
      - name: Print Custom Field
        run: echo "snow_chg_id:" ${{ github.event.client_payload.snow_chg_id }}
      - name: Print assignee
        run: echo "Summary:" ${{ github.event.client_payload.assignee }}
      - name: Print description
        run: echo "Summary:" ${{ github.event.client_payload.description }}

