name: Triggered from Jira

on:
 workflow_dispatch:
  # repository_dispatch:
  #   types: do-something # Ensure this matches `event_type` in Jira
  
    
jobs:
  process_jira_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
           python-version: "3.9"  # Uses latest Python 3
 
      - name: Install dependencies (if needed)
        run: pip install requests  # Add dependencies if required

      - name: run the qtest code
        id: qtest_test_case
        run: |
          set -x
          response=$(curl --location 'https://equinor.qtestnet.com/api/v3/projects/119783/test-cases?parentId=9279526&page=1&expandProps=true&expandSteps=no' \
                    --header 'Authorization: Bearer ca42f96c-8c1e-4868-b0cd-5d1f7ad57f21')
          RESULT=$(python -c "import json, sys; data = json.loads(sys.argv[1]); ids = [(item['id'], item['name']) for item in data]; print(ids)" "$response")
          echo "RESULT=$RESULT" >> $GITHUB_ENV
          # echo $RESULT

      - name: Process Data in Python
        run: |
          python3 - <<EOF
          import json
          import os

          # Get the environment variable
          val = os.getenv("RESULT", "[]")  # Default to empty list if missing

          # Convert JSON string back to list
          try:
              for item in val:
                  print(f"Test ID: {item[0]}, Test Name: {item[1]}")
          except json.JSONDecodeError as e:
              print(f"Error parsing JSON: {e}")
          EOF

   
           
                        
      
      
      # - name: Print Full Payload
      #   run: echo "${{ toJson(github.event.client_payload) }}"

      # - name: Print Issue Key
      #   run: echo "Issue Key=${{ github.event.client_payload.issueKey }}"

      # - name: Print Summary
      #   run: echo "Summary=${{ github.event.client_payload.summary }}"

      # - name: Print env values
      #   run: cat $GITHUB_ENV

      # - name: Print Custom Field
      #   run: echo "snow_chg_id:" ${{ github.event.client_payload.snow_chg_id }}

      # - name: Print assignee
      #   run: echo "Assignee:" ${{ github.event.client_payload.assignee }}

      # - name: Print description
      #   run: echo "Description:" ${{ github.event.client_payload.description }}

      # - name: Update charm id in jira
      #   shell: bash
      #   # env:
      #   #   ISSUE_KEY: "TESTING-18"
      #   #   CHARM_ID: "1234567"  # Set CHARM_ID directly
      #   run: |
      #      response_code=$(curl -o /dev/null -s -w "%{http_code}" -X PUT \
      #        -u "${{secrets.JIRA_API_USER}}:${{secrets.JIRA_API_TOKEN}}" \
      #        -H "Content-Type: application/json" \
      #        -d '{
      #              "fields": {
      #                "customfield_10440": "'"123456"'"
      #              }
      #            }' \
      #        "https://your-domain.atlassian.net/rest/api/3/issue/TESTING-18")
      #      if [ "$response_code" -eq 200 ] || [ "$response_code" -eq 204 ]; 
      #      then
      #        echo "Success: The request was successful with status code $response_code."
      #      else
      #        echo "Error: The request failed with status code $response_code"
      #        exit 1
      #      fi

      # - name: Generate OAuth Token
      #   id: generate_token
      #   # env:
      #   #    JIRA_API_USER: ${{ secrets.JIRA_API_USER }}
      #   #    JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      #   #    # SAP_CLIENT_ID: ${{ secrets.SAP_CLIENT_ID }}
      #      # SAP_CLIENT_SECRET: ${{ secrets.SAP_CLIENT_SECRET }}
      #      # SAP_TOKEN_URL: ${{ secrets.SAP_TOKEN_URL }}
      #      # SAP_CLIENT_ID: h3kpK9Dsh8i51WTZRA50Se7H4GTEcQ3x
      #      # SAP_CLIENT_SECRET: tttRQgsmV4ocIuJa
      #      # SAP_TOKEN_URL: https://devequinor.test.apimanagement.eu10.hana.ondemand.com:443/v2/oauth2/token
      #   run: |
      #         response=$(curl -X GET \
      #         -u "${{ secrets.JIRA_API_USER }}:${{ secrets.JIRA_API_TOKEN }}" \
      #         -H "Content-Type: application/json" \
      #          https://eqn-nextgen.atlassian.net/rest/api/2/issue/TESTING-18| grep -o '"customfield_10440":"[^"]*"' | sed 's/.*:"//;s/"$//')
      #         echo $response
      #         echo "response_code=$response_code" >> $GITHUB_ENV

      # - name: Check response code and echo success
      #   run: |
      #     if [ -n "$response_code" ]; then
      #       echo "Success"
      #       response_code=$(curl -o /dev/null -s -w "%{http_code}" -X PUT \
      #       -u "${{ secrets.JIRA_API_USER }}:${{ secrets.JIRA_API_TOKEN }}" \
      #       -H "Content-Type: application/json" \
      #       -d '{
      #             "fields": {
      #               "customfield_10440": "Charm_id_old:" $response_code,"charm_id_new: 1234567" 
      #             }
      #           }' \
      #       "https://eqn-nextgen.atlassian.net/rest/api/3/issue/TESTING-18")
      #     else
      #       response_code=$(curl -o /dev/null -s -w "%{http_code}" -X PUT \
      #       -u "${{ secrets.JIRA_API_USER }}:${{ secrets.JIRA_API_TOKEN }}" \
      #       -H "Content-Type: application/json" \
      #       -d '{
      #             "fields": {
      #               "customfield_10440": "'123455'"
      #             }
      #           }' \
      #       "https://eqn-nextgen.atlassian.net/rest/api/3/issue/TESTING-18")
      #     fi
      # - name: Generate OAuth Token
      #   id: generate_token
      #   run: |
      #     response=&(curl --location 'https://equinor.qtestnet.com/api/v3/projects/119783/test-cases?parentId=9279526&page=1&expandProps=true&expandSteps=no' \
      #               --header 'Authorization: Bearer ca42f96c-8c1e-4868-b0cd-5d1f7ad57f21')
      #     echo $response
      #     echo $response | jq '[.[] | {id: .id, name: .name}]'
      # - name: Check response code and echo success
      #   run: |
      #     if [ -n "${{env.response}}" ]; then
      #       echo "Success: Found response"
      #       response_code=$(curl -o /dev/null -s -w "%{http_code}" -X PUT \
      #         -u "${{ secrets.JIRA_API_USER }}:${{ secrets.JIRA_API_TOKEN }}" \
      #         -H "Content-Type: application/json" \
      #         -d "{
      #               \"fields\": {
      #                 \"customfield_10440\": \"Charm_id_old: ${{env.response}}, charm_id_new: 1234567\"
      #               }
      #             }" \
      #         "https://eqn-nextgen.atlassian.net/rest/api/3/issue/TESTING-18")
      #     else
      #       echo "No response found, using default value"
      #       response_code=$(curl -o /dev/null -s -w "%{http_code}" -X PUT \
      #         -u "${{ secrets.JIRA_API_USER }}:${{ secrets.JIRA_API_TOKEN }}" \
      #         -H "Content-Type: application/json" \
      #         -d "{
      #               \"fields\": {
      #                 \"customfield_10440\": \"123455\"
      #               }
      #             }" \
      #         "https://eqn-nextgen.atlassian.net/rest/api/3/issue/TESTING-18")
      #     fi
      #     echo "Response Code: $response_code"
         
   
           # echo "Token retrieved successfully"
           # echo "Access Token: $token"
   
           # # Save the token as an output for later steps
           # echo "token=$token" >> $GITHUB_ENV
           # curl -s -X POST \
           #  -u "${{ secrets.JIRA_API_USER }}:${{ secrets.JIRA_API_TOKEN }}" \
           # -H "Content-Type: application/json" \
           # --data '{
           #   "transition": {
           #     "id": "151"
           #   }
           # }' \
           # "https://eqn-nextgen.atlassian.net/rest/api/3/issue/TESTING-18/transitions"

         
